Fix user default entity injection
pluginsGLPI/datainjection pull request #433
Opened 2024-10-16 10:19 UTC by Lainow

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.
- [ ] I have added tests (when available) that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !34752
- Here is a brief description of what this PR does

Fix default entity insertion for a user

2024-10-17 05:52 UTC, Rom1-B commented on inc/userinjection.class.php
> +        $options['displaytype']    = ["dropdown"       => [3, 77, 79, 81, 82],
Can you please comment on what each ID stands for?
```suggestion
        $options['displaytype']    = [
            "dropdown"       => [
                3,  // ...
                77, // ...
                79, // ...
                81, // ...
                82, // ...
            ],
```

2024-10-17 10:05 UTC, stonebuzz approved these changes

2024-10-17 10:05 UTC, stonebuzz commented
waiting from customer feedback

2024-10-18 12:56 UTC, stonebuzz approved these changes
seems good

2024-10-18 12:56 UTC, stonebuzz commented
waiting from customer feedback

2024-10-22 08:21 UTC, Rom1-B requested changes

2024-10-22 08:21 UTC, Rom1-B commented on inc/commoninjectionlib.class.php
> +                        if (strpos($value, '>')) {
Technically, a name can't have a ‘>’?
Perhaps it would be easier to search if `name = $value OR completename = $value`?

2024-10-22 08:25 UTC, trasher commented on inc/commoninjectionlib.class.php
> +                        if (strpos($value, '>')) {
A `>` in a completename means a hierarchy as far as I remember

2024-10-22 08:31 UTC, Rom1-B commented on inc/commoninjectionlib.class.php
> +                        if (strpos($value, '>')) {
Yes, I agree, but I mean that the (simple) name of an entity can contain a ‘>’, it's not blocked.
![image](https://github.com/user-attachments/assets/a021cafe-9f58-4a55-88c1-6dd0d8fb5bb6)

2024-10-23 13:16 UTC, trasher commented
Hostely, I do not know this plugin, nor the way it works... But as far as I understand, you've replace `completename` with `name`; this sounds like an important change that mays broke the way it works until now.

Since there is no unit tests, I really do not know if it has an impact... But I guess we should be sure before changing that kind of things.

2024-10-29 07:37 UTC, stonebuzz approved these changes
Can you get the customer to validate this new version?

2024-11-04 14:31 UTC, Lainow commented
> Can you get the customer to validate this new version?

All good for him

2024-11-05 08:11 UTC, stonebuzz requested changes

2024-11-05 08:11 UTC, stonebuzz commented on inc/commoninjectionlib.class.php
> +                    if ($item->getType() == 'Entity') {
can you add a comment to quickly explain why we manage a specific case (Entity)

2024-11-06 09:11 UTC, stonebuzz commented
a more precise comment on the difficulty of going through the GLPI core (restriction of entities etc ...)

2024-11-07 15:06 UTC, Rom1-B commented on inc/commoninjectionlib.class.php
> +                    if ($item->getType() == 'Entity') { // This will block the creation of entities. In addition, the findID method only searches for an entity if it is directly a sub-entity of the r
```suggestion
                    if ($item->getType() == 'Entity') { // Blocks entity creation. The findID method only searches for direct sub-entities of the root, not deeper levels.
```

2024-11-08 10:23 UTC, stonebuzz approved these changes

2024-11-27 15:19 UTC, Rom1-B approved these changes

2024-11-28 08:33 UTC, stonebuzz commented
@Lainow 

can you adapt `CHANGELOG.md`

2024-11-28 14:35 UTC, merged