fix: update default user profile is not attribute
pluginsGLPI/datainjection pull request #434
Opened 2024-10-16 13:08 UTC by MyvTsv

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.
- [x] I have added tests (when available) that prove my fix is effective or that my feature works.

## Description

Ticket #34792
The default user profile is not updated

## Screenshots (if appropriate):

2024-10-17 10:10 UTC, stonebuzz requested changes

2024-10-17 10:10 UTC, stonebuzz commented on inc/userinjection.class.php
> +                }
This is always run (`$profile` alwys have `users_id`, `profiles_id`, `entities_id`)
so it's always updated `'is_default_profile' => 1`

2024-10-17 10:10 UTC, stonebuzz commented on inc/userinjection.class.php
> +                ]);
and this is always run too

2024-10-21 08:21 UTC, Lainow commented on inc/userinjection.class.php
> +                'entities_id' => $values['User']['entities_id'],
Add `‘profiles_id’ => $values[‘User’][‘profiles_id’],` to your crit. Because if the user already has a right, this part of will overwrite it to add the imported right. Furthermore, if the user has several rights, `getFromDbByCrit` will return an error because it will find several results instead of just one.

2024-10-21 08:22 UTC, Lainow commented on inc/userinjection.class.php
> +                    'profiles_id' => $values['User']['profiles_id'],
After the previous modification you can remove this `‘profiles_id’ => $values[‘User’][‘profiles_id’],`

2024-10-21 09:02 UTC, Lainow approved these changes

2024-10-28 10:37 UTC, Rom1-B requested changes

2024-10-28 10:37 UTC, Rom1-B commented on inc/userinjection.class.php
> +                'prodiles_id' => $values['User']['profiles_id']
I doubt it worked with the typo:
```suggestion
                'profiles_id' => $values['User']['profiles_id']
```
Can you retest the scenario described by @Lainow ?

2024-11-15 09:55 UTC, stonebuzz commented
following user feedback i close

2024-11-15 09:55 UTC, closed without merging